/*
Stickerio API

MMO RTS Stickerio game on an API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generated

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1CityResources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CityResources{}

// V1CityResources struct for V1CityResources
type V1CityResources struct {
	SticksCountBase int64 `json:"sticksCountBase"`
	SticksCountEpoch int64 `json:"sticksCountEpoch"`
	CirclesCountBase int64 `json:"circlesCountBase"`
	CirclesCountEpoch int64 `json:"circlesCountEpoch"`
}

type _V1CityResources V1CityResources

// NewV1CityResources instantiates a new V1CityResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CityResources(sticksCountBase int64, sticksCountEpoch int64, circlesCountBase int64, circlesCountEpoch int64) *V1CityResources {
	this := V1CityResources{}
	this.SticksCountBase = sticksCountBase
	this.SticksCountEpoch = sticksCountEpoch
	this.CirclesCountBase = circlesCountBase
	this.CirclesCountEpoch = circlesCountEpoch
	return &this
}

// NewV1CityResourcesWithDefaults instantiates a new V1CityResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CityResourcesWithDefaults() *V1CityResources {
	this := V1CityResources{}
	return &this
}

// GetSticksCountBase returns the SticksCountBase field value
func (o *V1CityResources) GetSticksCountBase() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SticksCountBase
}

// GetSticksCountBaseOk returns a tuple with the SticksCountBase field value
// and a boolean to check if the value has been set.
func (o *V1CityResources) GetSticksCountBaseOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SticksCountBase, true
}

// SetSticksCountBase sets field value
func (o *V1CityResources) SetSticksCountBase(v int64) {
	o.SticksCountBase = v
}

// GetSticksCountEpoch returns the SticksCountEpoch field value
func (o *V1CityResources) GetSticksCountEpoch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SticksCountEpoch
}

// GetSticksCountEpochOk returns a tuple with the SticksCountEpoch field value
// and a boolean to check if the value has been set.
func (o *V1CityResources) GetSticksCountEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SticksCountEpoch, true
}

// SetSticksCountEpoch sets field value
func (o *V1CityResources) SetSticksCountEpoch(v int64) {
	o.SticksCountEpoch = v
}

// GetCirclesCountBase returns the CirclesCountBase field value
func (o *V1CityResources) GetCirclesCountBase() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CirclesCountBase
}

// GetCirclesCountBaseOk returns a tuple with the CirclesCountBase field value
// and a boolean to check if the value has been set.
func (o *V1CityResources) GetCirclesCountBaseOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CirclesCountBase, true
}

// SetCirclesCountBase sets field value
func (o *V1CityResources) SetCirclesCountBase(v int64) {
	o.CirclesCountBase = v
}

// GetCirclesCountEpoch returns the CirclesCountEpoch field value
func (o *V1CityResources) GetCirclesCountEpoch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CirclesCountEpoch
}

// GetCirclesCountEpochOk returns a tuple with the CirclesCountEpoch field value
// and a boolean to check if the value has been set.
func (o *V1CityResources) GetCirclesCountEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CirclesCountEpoch, true
}

// SetCirclesCountEpoch sets field value
func (o *V1CityResources) SetCirclesCountEpoch(v int64) {
	o.CirclesCountEpoch = v
}

func (o V1CityResources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CityResources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sticksCountBase"] = o.SticksCountBase
	toSerialize["sticksCountEpoch"] = o.SticksCountEpoch
	toSerialize["circlesCountBase"] = o.CirclesCountBase
	toSerialize["circlesCountEpoch"] = o.CirclesCountEpoch
	return toSerialize, nil
}

func (o *V1CityResources) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sticksCountBase",
		"sticksCountEpoch",
		"circlesCountBase",
		"circlesCountEpoch",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1CityResources := _V1CityResources{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1CityResources)

	if err != nil {
		return err
	}

	*o = V1CityResources(varV1CityResources)

	return err
}

type NullableV1CityResources struct {
	value *V1CityResources
	isSet bool
}

func (v NullableV1CityResources) Get() *V1CityResources {
	return v.value
}

func (v *NullableV1CityResources) Set(val *V1CityResources) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CityResources) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CityResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CityResources(val *V1CityResources) *NullableV1CityResources {
	return &NullableV1CityResources{value: val, isSet: true}
}

func (v NullableV1CityResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CityResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


